export const REQUEST_CAR_BODY = 'REQUEST_CAR_BODY'
export const RECEIVE_CAR_BODY = 'RECEIVE_CAR_BODY'
export const CAR_BODY_SELECTION = 'CAR_BODY_SELECTION'

export const NEXT_FILTER = 'NEXT_FILTER'

export const REQUEST_CAR_FUEL = 'REQUEST_CAR_FUEL'
export const RECEIVE_CAR_FUEL = 'RECEIVE_CAR_FUEL'

export const REQUEST_CAR_FEATURE = 'REQUEST_CAR_FEATURE'
export const RECEIVE_CAR_FEATURE = 'RECEIVE_CAR_FEATURE'
export const CAR_FEATURE_SELECTION = 'CAR_FEATURE_SELECTION'
